### ISSUE TITLE
Request custom stop - coding requests by apps

### ISSUE THREAD

**Issue by ChristianAGSE** [GSE-Project/SS2016-group1#64]

**Comment by rrosemann** [comment]
Before coding can start, some questions still need to be resolved. I put them here for everyone to think about it (@mbaniasad, maybe you can have a look at it)
- How do we determine the bus which will do the request? The easiest ways would be to either check the schedules and pick the bus which is supposed to be close to the custom location at the given time. Or we use the GPS locations and determine the closest bus. I would suggest the first one, because it is sort of a long term prediction, whereas the second idea only works for very short-termed custom stops.
- When will the missing interfaces be given? I could also prepare some suggestions, if you like.
- Do we need a timestamp for our data structure? Maybe to judge that the request is not completely outdated? Or is it enough to use the time given by the customer for that?

**Comment by Sriramk88** [comment]
@ricarda42 I think our interface would be something like this

./customStops
{
  "customStops":
     [{
       "requestID": Number,
       "reqLocation": {"type": "Point", "coordinates": [Double,Double]},
       "reqTime": Number,
       "lineID": Number,  
       "numOfPassengers": Number,
       "busID": Number,
       "accpt_Rej": String
       "reqComplete": String
       "info": {
        "custName": String,
        "address": String,
        "assistance": [String],
        }
     }],
       "timeStamp": timeStamp
}

**Comment by rrosemann** [comment]
I created a branch developmentIt3 for the coding, so we should all commit our code to this branch.

**Comment by Sriramk88** [comment]
@mbaniasad @razadfki We are facing some technical issues when using session.save to dump the data. We'll check with @maybeec about it tomorrow.

**Comment by razadfki** [comment]
@Sriramk88 thanks for mentioning me, I'll be working on this issue tomorrow.

**Comment by Sriramk88** [comment]
We have a working code and will proceed with the integration testing.

**Comment by Sriramk88** [comment]
Closing #64
