### ISSUE TITLE
Update requirements documentation

### ISSUE THREAD

**Issue by rrosemann** [GSE-Project/SS2016-group1#85]
Check all traceability matrices and the requirements doc if they are up-to-date.
Include new methods as system functions in requirements doc:
- delete method
- status handling
- possibly: automated delete
- possibly: automated decline

**Comment by mbaniasad** [comment]
I have assigned @mzeen @bonkilejay to this in [here](https://github.com/GSE-Project/SS2016-group3/issues/69) if guys have no time you can also discuss with @ricarda42 and get ready for it.

**Comment by rrosemann** [comment]
All changes required are done, please review! Documents changed are "Update Traceability to SFs" and "Updated Traceability matrix" and the system functions in the requirements doc.
@mbaniasad Please assign a reviewer.

**Comment by razadfki** [comment]
@ricarda42 in **Update Traceablility matrix** , I suspect the IC_C1 in the google doc is not up-to-date, because in both of the IC 2 & 3, they are not referring to _available Seats_ at all i.e., **SF_S14**.
but it should not concern us(I guess..!). Just mentioning here.
also, they are not referring to **SF_S16** in **IC_C4**, and this is regarding status which needs to be discussed ye.?

**Comment by rrosemann** [comment]
Actually IC_C4 is just about sending a custom stop, as I understand it. So requesting the status is not necessarily part of this. They don't seem to have an interaction case for requesting the status.

**Comment by razadfki** [comment]
okay, I reviewed the documents and set the status completed "anyway".

**Comment by rrosemann** [comment]
Then we can close this, right?

**Comment by razadfki** [comment]
@ricarda42 just to a side note, I did reviewed some of the SF in the docs.
Also, if I look into the description of this issue then it does not say things only about the two documents file I just reviewed. there are more!
