### ISSUE TITLE
Fetching request states with just deviceId

### ISSUE THREAD

**Issue by themetalone** [GSE-Project/SS2016-group1#90]
Hello *, 

during playing with your server I found that your server (current build from Iteration 3 branch) responds to 

```
?requestId=123
?requestId=123&deviceId=somePc
```

but not to just `?deviceId=xyz`

Furthermore I found that when providing both request and device id the later one is simply ignored. i.e.
`requestId=10000000&deviceId=somePC` returns the same request state as does `requestId=10000000&deviceId=asdlkfjah`.
### Question

Could you implement/fix the server response so we get all requests associated with the device id when accessing `/customStops?deviceId={device_id}`?

Thanks a lot. 

PS: [your wiki](https://github.com/GSE-Project/SS2016-group1/wiki/Server-interfaces#custm-stop-interfaces) states that you expect `id` instead of `requestId`.

**Comment by rrosemann** [comment]
I just tried to replicate your errors with the current build from Iteration 3 branch and I don't have any problems. Putting `?requestId=1&deviceId=7` returns the sample custom stop whereas `?requestId=1&deviceId=mnnk` returns an empty list. With `?deviceId=7` only I get all custom stops for deviceId=7.
Maybe you should check that you really have the current version.
Thanks for reporting the inconsistency with the server interface. If you are using `requestId` in your code, we can change the interface document. Otherwise we could also change our code again...

**Comment by themetalone** [comment]
Well, this is strange. But if it works for you.. 

I implemented `requestId` since it worked with the serve I used for testing

PS: It works for the client too, but Postman thinks otherwise..
