### ISSUE TITLE
cancellation of a custom stop 

### ISSUE THREAD

**Issue by mbaniasad** [GSE-Project/SS2016-group1#94]
- [x] I talk to @maybeec  about it. do we need a script to delete customstops after a while?

**Comment by mbaniasad** [comment]
@maybeec when can we meet?

**Comment by maybeec** [comment]
Now? Yes,  come along

-------- Ursprüngliche Nachricht --------
Von: mohammad baniasad notifications@github.com
Gesendet: 4. Juli 2016 10:01:55 MESZ
An: GSE-Project/SS2016-group1 SS2016-group1@noreply.github.com
CC: Malte Brunnlieb maltebrunnlieb@web.de, Mention mention@noreply.github.com
Betreff: Re: [GSE-Project/SS2016-group1] cancellation of a custom stop (#94)

@maybeec when can we meet?

---

**Comment by mbaniasad** [comment]
Not now. Tomorrow

**Comment by maybeec** [comment]
ok, what about half an hour at 11:30?

In general working with periodic automated tasks, the OASP4J encourages you to use a batch (https://github.com/oasp-forge/oasp4j-wiki/wiki/guide-batch-layer).
However, depending on your requirements, it might be not the best idea. Correct me, but you would like to remove all visited custom stops after the bus has finished his line, would you?
Otherwise, there might be too many custom stops to be displayed on the clients.

So I think there are two solutions:
1. Save all custom stops on the server side and running a periodic (dayly?) batch to remove all (or just visited?) entries requested for a time in the past.
   - this may lead to the necessity of a filter mechanism to be in place allowing the clients to retrieve all custom stops or just retrieve the custom stops of the next hour to be easily displayable on a map
2. Save all custom stops on the server side and let the clients trigger a cleanup of visited custom stops after finishing their root.
   - this will imply to most likely introduce a reference from a custom stop to a line id (visited by) to specifically remove just the custom stops visited by the finished line.
   - this will imply to not have any historic data anymore about custom stops (which may be interesting for data analysis to introduce/change e.g. planned stops in future)

@GSE-Project/group1 @GSE-Project/group2 @GSE-Project/group3 :
Maybe, you already know the requirements, but you should align on them to find the right solution.

**Comment by mbaniasad** [comment]
Good tomorrow at11:30

**Comment by razadfki** [comment]
since, it's been mentioned in #88 if that's going to be closed then please! consider this as well.

**Comment by razadfki** [comment]
@ricarda42 what about this one? since #88 is closed now. because it does have deadline 12 July.

**Comment by razadfki** [comment]
since we got a response from Steffen, according to which we should simply mark the status cancelled and which is already the implemented functionality. It should be closed by now.
